version: "3"
services:
  web:
    build: .
    ports:
    - "5090:5050"
    volumes:
    - .:/code
    links:
    - mongo

  mongo:
    image: mongo:4.2
    ports:
      - '27030:27017'
    volumes:
      - ./data:/data/db

