# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  server:
    docker:
      # specify the version you desire here
      - image: circleci/node:10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:4.0.3

    working_directory: ~/express-generator

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependency-cache-server-{{ checksum "./server/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependency-cache-server-

      - run: yarn --frozen-lockfile

      - save_cache:
          key: dependency-cache-server-{{ checksum "./server/package.json" }}
          paths:
            # Save the yarn cache folder so we can cache cypress as well.
            - ~./server/node_modules

      # Run typescript
      - run: cd server && yarn tsc
      # run tests!
      - run:
          name: Run tests
          command: cd server && yarn test

  client:
    docker:
      # specify the version you desire here
      - image: circleci/node:10

    working_directory: ~/express-generator/client

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependency-cache-client-{{ checksum "./client/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependency-cache-client-

      - run:
          name: Install client dependencies
          command: cd client && yarn --frozen-lockfile

      - save_cache:
          key: dependency-cache-client-{{ checksum "./client/package.json" }}
          paths:
            - ./client/node_modules

      # run tests!
      - run:
          name: Run client tests
          command: cd client && yarn test

workflows:
  Test Server and Client:
    jobs:
      - server
